name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: ubuntu-ruby-${{ matrix.ruby-version }}
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ["3.2", "3.1"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "12"
      - name: Install dependencies
        run: bundle install
      - name: Configure Datadog Test Optimization
        uses: datadog/test-visibility-github-action@v2
        with:
          languages: ruby
          api_key: ${{ secrets.DD_API_KEY }}
          site: datadoghq.eu
      - name: Runs tests
        run: bundle exec rake test
        env:
          TEST: true
          DD_TEST_SESSION_NAME: middleman-unit
